import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import PageCore from "./PageCore";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  image,
}: Readonly<{
  children: React.ReactNode;
  image: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-dvh w-dvw flex flex-col overflow-auto ${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageCore>{children}</PageCore>
        <div>{image}</div>
      </body>
    </html>
  );
}
